const	string	MSB_STRING_BANK_DATA_CONFIG		=	"$profile:MSB\\CONFIGS\\MSB_STRING_BANK_DATA_CONFIG.txt";
const	string	MSB_STRING_BANK_HOT_KEY_CONFIG	=	"$profile:MSB\\CONFIGS\\MSB_STRING_BANK_HOT_KEY_CONFIG.txt";
const	string	MSB_STRING_BANK_FOLDER			=	"$profile:MSB\\MSB_STRING_BANK_FOLDER\\";
const	string	MSB_STRING_BANK_PREFIX			=	"BANKING_";