const	int	MSB_INT_STC_PACKET_ID_BANK				=	5;
const	int	MSB_INT_CTS_PACKET_ID_BANK				=	5;

const	int	MSB_INT_STC_PACKET_ID_BANK_DATA			=	10;
const	int	MSB_INT_STC_PACKET_ID_BANK_HOT_KEY		=	15;
const	int	MSB_INT_STC_PACKET_ID_BANK_VALUE_BANK		=	20;
const	int	MSB_INT_STC_PACKET_ID_BANK_VALUE_CASH		=	25;
const	int	MSB_INT_STC_PACKET_ID_BANK_ERROR			=	30;
const	int	MSB_INT_STC_PACKET_ID_BANK_CLEAR_PLAYERS	=	35;
const	int	MSB_INT_STC_PACKET_ID_BANK_PLAYER			=	40;

const	int	MSB_INT_CTS_PACKET_ID_BANK_GET_PLAYERS	=	110;
const	int	MSB_INT_CTS_PACKET_ID_BANK_GET_CASH		=	115;
const	int	MSB_INT_CTS_PACKET_ID_BANK_GET_BANK		=	120;
const	int	MSB_INT_CTS_PACKET_ID_BANK_CASH_TO_BANK	=	125;
const	int	MSB_INT_CTS_PACKET_ID_BANK_BANK_TO_CASH	=	130;
const	int	MSB_INT_CTS_PACKET_ID_BANK_TO_OTHER_BANK	=	135;
const	int	MSB_INT_CTS_PACKET_ID_BANK_OPEN			=	140;
const	int	MSB_INT_CTS_PACKET_ID_BANK_CLOSE			=	145;